packages:
  - packages/core
  - packages/preview-file
  - packages/plugins/*
  - packages/adapters/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

patchedDependencies:
  pptx-browser@4.1.5: patches/pptx-browser@4.1.5.patch
